### ISSUE TITLE
Add broadcast collective operation

### ISSUE THREAD

**Issue by tkilias** [exasol/advanced-analytics-framework#104]
# Background

- The ML Frameworks need to exchange connection information between all UDF instances of a UDF call to build a cluster for distributed machine learning
- To send information from one UDF instance to all other UDF instances, we need to implement the [Broadcast](https://en.wikipedia.org/wiki/Collective_operation#Broadcast) pattern 
- Tips: 
  - Count the rounds of collective operations and add them to the messages in case of strugglers or resends.

**Comment by redcatbear** [comment]
Torsten is on vacation.

**Comment by ckunki** [comment]
See Review by @Nicoretti
