### ISSUE TITLE
AAF: Update Python

### ISSUE THREAD

**Issue by ckunki** [exasol/advanced-analytics-framework#170]
We released [slct 0.19.0](https://github.com/exasol/script-languages-container-tool/releases/tag/0.19.0) and should use it here.

## Acceptance criteria

* [x] Update to Python 3.10: Already done in [#171](171)
* [x] Update dependencies: Already done in [#171](171)
* [x] Update slct to 0.19.0

**Comment by tkilias** [comment]
slct version depends on pytest-slc plugin. Will be done by https://github.com/exasol/advanced-analytics-framework/issues/174
