### ISSUE TITLE
Add function register_query_handler_inside_udf

### ISSUE THREAD

**Issue by ckunki** [exasol/advanced-analytics-framework#197]
### Acceptance Criteria
* The register function e.g. `register_query_handler_inside_udf()` is added to AAF python code 
* The register function should add the udf to module `exasol_advanced_analytics_framework.custom`, so we need to add an empty module at this place
* The register function is included in the adhoc example of the user guide incl. a comment that it only needs to be called when defining the query handler inside of a UDF (= adhoc)

**Comment by tkilias** [comment]
the register_query_handler_inside_udf function should add the udf to module exasol_advanced_analytics_framework.custom, so we need to add an empty module at this place

**Comment by tkilias** [comment]
duplicate of https://github.com/exasol/advanced-analytics-framework/issues/190
