### ISSUE TITLE
Clean package names and directory structure

### ISSUE THREAD

**Issue by ckunki** [exasol/advanced-analytics-framework#203]
[Comment from @Nicoretti](https://github.com/exasol/advanced-analytics-framework/pull/202/files#r1810784044) on PR #202 

```python 
from exasol_advanced_analytics_framework.udf_framework.query_handler_runner_udf \
    import QueryHandlerRunnerUDF
```

Naming is slightly out of control, the full name contains:
* 3x  udf
* 2x query
* 2x framework
* 2x handler
* 2x runner

which results in the need to break the import line ...

**Comment by ckunki** [comment]
### Proposed renaming

![image](https://github.com/user-attachments/assets/7a8f5b66-1fe2-4954-b67d-344e11b1eb4e)

**Comment by tkilias** [comment]
udf communication and the query handlers are two seperate features, that should get their own  package under exasol.aaf. or however we call it. I think, actually exasol.analytics might be not the worst idea.

**Comment by ckunki** [comment]
I also was considering `exasol.analytics` and am fine with it.
Abbreviating everything (e.g. to `aaf`) might also not always be the best idea.

**Comment by ckunki** [comment]
> udf communication and the query handlers are two seperate features, that should get their own package 

They have (see picture containing `udf/communication` and `udf/query_handler`). 
The only things I moved directly under `udf` are `connection_lookup.py` and `dynamic_modules.py`. 
But I am happy to move these two files to any other position, as well.

**Comment by tkilias** [comment]
The question is more, if the query handler has directly something to do with udfs. Yes, it can be used together with UDFs, but it can also be used without.

**Comment by tkilias** [comment]
Suggestion for structure below analytics:
- udf
  - communcation
  - autoudf
  - utils
    - exasol_data_science_utils_python/udf_utils/udf_context_wrapper.py
    - exasol_data_science_utils_python/udf_utils/iterator_utils.py
- query_handler exasol_advanced_analytics_framework/query_handler
  - udf exasol_advanced_analytics_framework/udf_framework
- sqlexecutor 
 - exasol_data_science_utils_python/udf_utils/sql_executor.py
 - exasol_data_science_utils_python/udf_utils/pyexasol_sql_executor.py
 - testing 
   - exasol_advanced_analytics_framework/udf_utils/testing/mock_sql_executor.py
   - exasol_data_science_utils_python/udf_utils/testing/mock_result_set.py
- utils exasol_data_science_utils_python/utils
- schema


remove exasol_data_science_utils_python/udf_utils/testing/mock_sql_executor.py

**Comment by ckunki** [comment]
Interpreting indent level: 

- sqlexecutor
  - exasol_data_science_utils_python/udf_utils/sql_executor.py
  - exasol_data_science_utils_python/udf_utils/pyexasol_sql_executor.py

**Comment by ckunki** [comment]
Updated Image: 

![image](https://github.com/user-attachments/assets/02c5e364-2853-4bf8-aee3-a3559837c2b4)

**Comment by ckunki** [comment]
Additional renaming:
![image](https://github.com/user-attachments/assets/368a8b94-afe4-446f-ae2e-4ffcfb2f3d8a)

**Comment by ckunki** [comment]
Additional renamings:
* `query.handler` &rarr; `exasol/analytics/query_handler`
* `query_result` &rarr; `exasol/analytics/query/handler/result`
* `exasol/analytics/deployment/` &rarr; `exasol.analytics.query_handler/deployment`
* `exasol/analytics/deploy.py` &rarr; `exasol.analytics.query_handler/deployment/deploy.py`
* `exasol/analytics/slc.py` &rarr; `exasol.analytics.query_handler/deployment/slc.py`
