### ISSUE TITLE
Fix mypy warnings

### ISSUE THREAD

**Issue by ckunki** [exasol/advanced-analytics-framework#221]
https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
https://mypy.readthedocs.io/en/stable/running_mypy.html

**Comment by ckunki** [comment]
I found some classes initializing some of their attributes after `__init__()`
Other methods access the attributes that might be uninitialized.

Class [BackgroundListenerThread](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/udf/communication/peer_communicator/background_listener_thread.py)
* `self._register_peer_connection`, `RegisterPeerConnection()`
* `self._out_control_socket`
* `self._my_connection_info`

class QueryHandlerRunnerUDF
* `QueryHandlerRunnerState.input_query_query_handler_context` might be `None` while `self._wrap_return_query()` expects the argument not to be None
* `UDFParameter.temporary_schema_name` is Optional while `TopLevelQueryHandlerContext` expects the argument not to be None

[SQLStageGraphExecutionQueryHandlerState](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/query_handler/graph/stage/sql/execution/query_handler_state.py)
* `self._current_query_handler_context`
* `self._sql_stage_graph`

Class  [Communicator](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/udf/communication/communicator.py)
has some methods that potentially return None:
* `self._value`
* `self._multi_node_communicator`, `_create_multi_node_communicator()` -> `Optional[]`

[SQLStageGraphExecutionInput](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/query_handler/udf/runner/state.py)
still imports and uses as attribute type `AbstractBucketFSLocation`
* How can this be replaced by `bfs.path.PathLike`?

[call_udf.py](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/query_handler/udf/runner/call_udf.py)
contains `udf = QueryHandlerRunnerUDF(exa)`. Can we add `# type: ignore` here?


class `TopLevelQueryHandlerContext`, attribute `temporary_schema_name` is set from parameters to UDF.
I propose to change the type of this attribute from `str` to `Optional[str]`

**Comment by tkilias** [comment]
Regarding BackgroundListenerThread

They can only be initialized with a proper value in the run method, because the object gets transferred from one process to another process after the construction and only in the process then run is called.

Furthermore, I think there are more attributes for which the same is true , e g. self._in_control_socket, have a look at the _create_* methods that get called in run.

After the calls to the create methods in run they shouldn't be None anymore, before they could be None, I think. However, you might need to assert that they are not anymore before they get used otherwise, mypy might complain that they could be None. @tomuben had to do this in the itde.

**Comment by tkilias** [comment]
I think UDFParameter.temporary_schema_name can be None, because we don't validate the json in Lua regarding this and we probably don't need to. However, should be maybe checked , what we get if the json has no schema specified. However, the more I think, about it , also if it could be None , we need a value for it and that means either a default or an error. And, I think, tend to error here, that also should solve the complaint

**Comment by tkilias** [comment]
Regarding QueryHandlerRunnerState.input_query_query_handler_context assert in self._wrap_return_query() that it is not None, that solve the complaint

**Comment by tkilias** [comment]
Findings during review
- https://github.com/exasol/advanced-analytics-framework/issues/222

**Comment by tkilias** [comment]
Regarding UDFParameter

temporary_schema_name is of type str and not optional, we need to check if the value we get from the ctx is None and if yes throw an error message. https://github.com/exasol/advanced-analytics-framework/blob/fcbf1bf32a3868fe3d85063d4140c31b1f47a623/exasol/analytics/query_handler/udf/runner/udf.py#L178

**Comment by tkilias** [comment]
[SQLStageGraphExecutionQueryHandlerState](https://github.com/exasol/advanced-analytics-framework/blob/main/exasol/analytics/query_handler/graph/stage/sql/execution/query_handler_state.py)

- self._current_query_handler_context -> assert

**Comment by tkilias** [comment]
- [gather_operation multi_node_communicator](https://github.com/exasol/advanced-analytics-framework/blob/fcbf1bf32a3868fe3d85063d4140c31b1f47a623/exasol/analytics/udf/communication/gather_operation.py#L24)
  - make optional
  - add assert to constructor is None is only allowed when local rank > LOCAL_LEADER_RANK
  - add assert not None to usage of _multi_node_communicator

**Comment by ckunki** [comment]
The current unit tests for the classes in exasol.analytics.schema verify `TypeCheckError`s raised by typeguard.
This conflicts with the custom errors I introduced to be raised when asking an incomplete builde to build a type to meet the type hints. 

I see the following options
* O1) modify tests to verify the custom errors
* O2) modify the builders to raise `TypeCheckError`

**Comment by ckunki** [comment]
I fixed most of the findings in initial review batch 
More investigation was requested in 

* [exasol/analytics/query_handler/udf/runner/udf.py#L303](https://github.com/exasol/advanced-analytics-framework/pull/225/files#diff-23838995df920b9b7897730c7806315ee86d4a58cff113538efaa8bd34091d45R303)
`if query_columns is None:`
* [exasol/analytics/query_handler/python_query_handler_runner.py#L120](https://github.com/exasol/advanced-analytics-framework/pull/225/files#diff-82930bec52910a15af9dca8b3debe8f42c2a867fe62e095011bdface5a1af7b9R120)
` if self._state.input_query_query_handler_context is None:`
