### ISSUE TITLE
Add user guide

### ISSUE THREAD

**Issue by tkilias** [exasol/advanced-analytics-framework#26]
# Background

We need a User Guide for this repo. It should contain  the following sections:
  * Setup
  * Usage 
  * Implementation of algorithms

**Comment by ckunki** [comment]
During updating the User Guide, we faced the questions about Prebuilt SLCs. 
Ideally, a prebuilt SLC should not be required. 
When trying out this, we identified problems regarding module not found.

Additional options to bring the `CustomQueryHandler` into the UDF

1. Write QueryHandler and related factory into a file in /tmp and import this file
2. Use cloudpickle for serialization https://github.com/cloudpipe/cloudpickle
3. Dill could be an option

First we should try to import the module used during creation of the `QueryHandler` object also when deserializing the state.
