### ISSUE TITLE
Evaluate Event-Handler overhead

### ISSUE THREAD

**Issue by tkilias** [exasol/advanced-analytics-framework#3]
# Background

- We plan for the framework a Lua loop which executes SQL queries and runs an Event Handler which consume their result and issues new SQL Queries
- The Event handler should if possible be written in Python for that we need to start a Python UDF which can have a bit of overhead.
- Furthermore, the Event handler is stateful, that means in each call to the UDF we need to store the event handler in the BucketFS and load it during the next call.
- The total overhead should be best below 0.5 seconds or at least below a 1 second
- We also need to know how fast the distribution of the event handler state in the bucketfs is for cluster with more cores

**Comment by umitbuyuksahin** [comment]
[bfs_performance_results.pdf](https://github.com/exasol/advanced-analytics-framework/files/8185826/bfs_performance_results.pdf)
