### ISSUE TITLE
Adapt to the Lua Styleguide and introduce OOP

### ISSUE THREAD

**Issue by tkilias** [exasol/advanced-analytics-framework#48]
# Background

- https://github.com/exasol/advanced-analytics-framework/pull/47#discussion_r954668067
- https://github.com/exasol/advanced-analytics-framework/pull/47#discussion_r954747010
- https://github.com/exasol/advanced-analytics-framework/pull/47#discussion_r954964035
- https://github.com/exasol/advanced-analytics-framework/pull/47#discussion_r954696054
- https://github.com/exasol/advanced-analytics-framework/pull/47#discussion_r954965747

**Comment by redcatbear** [comment]
Shelved.
