### ISSUE TITLE
Store stacktrace during the creation of the query_handler_context

### ISSUE THREAD

**Issue by tkilias** [exasol/advanced-analytics-framework#70]
# Background

- It is difficult to identify which query_handler_context wasn't released, if we get an Exception. To allow better diagnostics, we should store the stack trace during the constructor call of the query_handler_context as a string inside the query_handler_context.

**Comment by ckunki** [comment]
Hello @tkilias : Could you please provide some more details on the current ticket?

**Comment by redcatbear** [comment]
Shelved.
